services:
  - type: web
    name: aiestimagent-api
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: VITE_API_URL
        value: https://aiestimagent-api.onrender.com
      - key: VITE_ML_URL
        value: https://aiestimagent.onrender.com
